Add new page for java
poker-bot-battles/website-frontend-legacy pull request #6
Opened 2024-02-17 09:20 UTC by lucasfth

2024-02-17 09:22 UTC, lucasfth commented on docs/index.html
> +                <a class="nav-button docs" href="./java.html">For Java documentation</a>
@fredpetersen har du måske mulighed for at se om de knapper jeg har brugt er okay? Jeg havde originalt tænkt mig at bruge knapperne der var i sidebar, men de baserer sig på hvilke tags man bruger. Så uden en kæmpe refactor kunne jeg umiddelbart ikke bruge dem (så brugte dem der blev brugt på forsiden)

2024-02-17 09:23 UTC, lucasfth commented
Hvis dem der reviewer også lige er sød at tjekke syntaksen.
Jeg er ret sikker på det er korrekt men ikke 100% sikker🤠

2024-02-19 07:21 UTC, fredpetersen requested changes
Nogle af ændringerne gælder også python documentation
sorry 😅

2024-02-19 07:21 UTC, fredpetersen commented on docs/java.html
> +                    This will put the bots current hand, with the table taken
```suggestion
                    This will put the bots current hand type, with the table taken
```

2024-02-19 07:21 UTC, fredpetersen commented on docs/java.html
> +                <pre><code class="language-java">if (currentBotHand == HandType.STRAIGHTFLUSH) {someAction();}</code></pre>
Kunne være man også skal skrive noget om at man kan sige "Denne her type eller bedre"
```suggestion
                <pre><code class="language-java">if (currentBotHand == HandType.STRAIGHTFLUSH) {someAction();}</code></pre>
                or you can compare the "value" of your handtype to another like this:
                <pre><code class="language-java">if (currentBotHand.getValue() >= HandType.STRAIGHTFLUSH.getValue()) {someAction();}</code></pre>
```

2024-02-19 07:21 UTC, fredpetersen commented on docs/java.html
> +                <pre><code class="language-java">if (("77+", "A8s+", "K9s+", "QTs+", "AJo+", "KQo").isHandInRange(obs.myHand)) {someAction();}</code></pre>
Det her er ikke helt rigtigt. Det er ikke en hand type du matcher til en range. Derudover er syntax lidt forkert
```suggestion
                    If you want to match you hand, to a "range" of cards, you
                    can do it like this:
                </p>
                <pre><code class="language-java">if (["77+", "A8s+", "K9s+", "QTs+", "AJo+", "KQo"]).isHandInRange(obs.myHand)) {someAction();}</code></pre>
```

2024-02-19 07:22 UTC, lucasfth commented
![Uploading here-we-go-again-gif.gif…]()

2024-02-19 07:22 UTC, lucasfth commented
![here-we-go-again-gif](https://github.com/poker-bot-battles/website-frontend/assets/94063597/2758849a-c371-4704-9746-c530fde08037)

2024-02-19 09:03 UTC, fredpetersen commented on docs/index.html
> +                <a class="nav-button docs" href="./java.html">For Java documentation</a>
Tror det her er fint. Ville nok eventuelt se på at fjerne margin i venstre side af knappen på denne side fordi det ser lidt fjollet ud :)

2024-02-22 18:17 UTC, lucasfth commented
@fredpetersen plz look

2024-02-22 18:27 UTC, fredpetersen approved these changes
lpgtm2s+

2024-02-22 18:27 UTC, merged